package BloodDonorInfo;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DataTable extends javax.swing.JFrame {

    ConnectionClass cc = new ConnectionClass();
    Connection con;

    void createIcon(){
        ImageIcon icon = new ImageIcon(getClass().getResource("icon.png"));
        this.setIconImage(icon.getImage());
    }
    
    public DataTable() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = cc.connector();
        refresh();
        
        createIcon();
        
        table.getTableHeader().setFont(new Font("Arial",Font.BOLD,18));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(Color.cyan);
        table.getTableHeader().setForeground(Color.MAGENTA);
    }

    void refresh() {
        try {
            DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM donorInfo");
            while (rs.next()) {
                String n = rs.getString("Name");
                String num = rs.getString("Number");
                String b = rs.getString("BloodGroup");
                String g = rs.getString("Gender");
                String a = rs.getString("Address");
                tableModel.addRow(new Object[]{n, "0" + num, b, g, a});
            }
            stmt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    void clear() {
        donorName.setText("");
        donorNumber.setText("");
        donorBlood.setText("");
        donorAddress.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        donorName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        donorBlood = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        donorNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donorAddress = new javax.swing.JTextArea();
        insert = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        profile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        donorGender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Data Table");
        setBackground(new java.awt.Color(255, 0, 102));
        setForeground(new java.awt.Color(255, 0, 102));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        donorName.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        donorName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(donorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 170, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Blood Group");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        donorBlood.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        donorBlood.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        donorBlood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                donorBloodKeyPressed(evt);
            }
        });
        getContentPane().add(donorBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 170, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        donorNumber.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        donorNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        donorNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                donorNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                donorNumberKeyReleased(evt);
            }
        });
        getContentPane().add(donorNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        donorAddress.setColumns(20);
        donorAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        donorAddress.setLineWrap(true);
        donorAddress.setRows(3);
        donorAddress.setTabSize(5);
        donorAddress.setWrapStyleWord(true);
        jScrollPane1.setViewportView(donorAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 180, -1));

        insert.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-insert-table-48.png"))); // NOI18N
        insert.setText("Insert");
        insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 130, -1));

        edit.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-edit-row-48.png"))); // NOI18N
        edit.setText("Edit");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 130, -1));

        update.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-update-64.png"))); // NOI18N
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 130, -1));

        delete.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-remove-48.png"))); // NOI18N
        delete.setText("Delete");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 130, 130, -1));

        search.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setToolTipText("Blood Group");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 70, 30));

        profile.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-user-male-100.png"))); // NOI18N
        profile.setText("Profile");
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 130, -1));

        table.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Number", "Blood", "Gender", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.setFillsViewportHeight(true);
        table.setFocusable(false);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(0, 255, 0));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(1).setMinWidth(130);
            table.getColumnModel().getColumn(1).setPreferredWidth(130);
            table.getColumnModel().getColumn(1).setMaxWidth(130);
            table.getColumnModel().getColumn(2).setMinWidth(80);
            table.getColumnModel().getColumn(2).setPreferredWidth(80);
            table.getColumnModel().getColumn(2).setMaxWidth(80);
            table.getColumnModel().getColumn(3).setMinWidth(100);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 740, 190));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        donorGender.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        donorGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(donorGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 170, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search Blood ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Blood Donor Information");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-power-off-button-64.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 230, 140, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-close-window-48.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/icons8-minus-64.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodDonorInfo/Data.jpeg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        try {
            String name = donorName.getText();
            String number = donorNumber.getText();
            String blood = donorBlood.getText();
            String gender;
            if (donorGender.getSelectedIndex() == 0) {
                gender = "Male";
            } else {
                gender = "Female";
            }
            String address = donorAddress.getText();
            if (name.isEmpty() || number.isEmpty() || blood.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill-up information !");
            } else {
                PreparedStatement pst = con.prepareStatement("INSERT INTO DonorInfo VALUES(?,?,?,?,?)");
                pst.setString(1, name);
                pst.setString(2, number);
                pst.setString(3, blood);
                pst.setString(4, gender);
                pst.setString(5, address);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Insertion successful !");
                pst.close();

            }
            refresh();
            clear();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
            int row = table.getSelectedRow();
            if (row >= 0) {
                String name = (String) tableModel.getValueAt(row, 0);
                String number = tableModel.getValueAt(row, 1).toString();
                String blood = (String) tableModel.getValueAt(row, 2);
                String address = (String) tableModel.getValueAt(row, 4);
                donorName.setText(name);
                donorNumber.setText(number);
                donorBlood.setText(blood);
                donorAddress.setText(address);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a row !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            String name = donorName.getText();
            String number = donorNumber.getText();
            String blood = donorBlood.getText();
            String gender;
            if (donorGender.getSelectedIndex() == 0) {
                gender = "Male";
            } else {
                gender = "Female";
            }
            String address = donorAddress.getText();
            if (name.isEmpty() || number.isEmpty() || blood.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill-up information !");
            } else {
                PreparedStatement pst = con.prepareStatement("UPDATE DonorInfo SET Name=?,BloodGroup=?,Gender=?,Address=? WHERE Number = ?");
                pst.setString(1, name);
                pst.setString(2, blood);
                pst.setString(3, gender);
                pst.setString(4, address);
                pst.setString(5, number);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated successfully !");
                pst.close();
                refresh();
            }
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
            int row = table.getSelectedRow();
            String number = tableModel.getValueAt(row, 1).toString();
            if (row >= 0) {
                int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this selected info ?", "Deleting Confirmation", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    String num = "DELETE FROM DonorInfo WHERE Number=" + number;
                    PreparedStatement pst = con.prepareStatement(num);
                    pst.execute();
                    pst.close();
                    refresh();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Please select a row !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select a row !");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        try {
            String s = search.getText();
            DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM donorInfo WHERE BloodGroup LIKE '" + s + "%'");
            while (rs.next()) {
                String n = rs.getString("Name");
                String num = rs.getString("Number");
                String b = rs.getString("BloodGroup");
                String g = rs.getString("Gender");
                String a = rs.getString("Address");
                tableModel.addRow(new Object[]{n, "0" + num, b, g, a});
            }
            stmt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchKeyReleased

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        char ch = evt.getKeyChar();
        if (Character.isLowerCase(ch)) {
            JOptionPane.showMessageDialog(null, "Please write in capital letter !");
            search.setText("");
        }
    }//GEN-LAST:event_searchKeyPressed

    private void donorBloodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_donorBloodKeyPressed
        char ch = evt.getKeyChar();
        if (Character.isLowerCase(ch)) {
            JOptionPane.showMessageDialog(null, "Please write in capital letter !");
            donorBlood.setText("");
        }
    }//GEN-LAST:event_donorBloodKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Profile p = new Profile();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_profileActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to close it ?", "Close Window", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void donorNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_donorNumberKeyPressed
        
    }//GEN-LAST:event_donorNumberKeyPressed

    private void donorNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_donorNumberKeyReleased
        char ch = evt.getKeyChar();
        if(Character.isAlphabetic(ch)){
            JOptionPane.showMessageDialog(null, "Please enter your number!");
        }
    }//GEN-LAST:event_donorNumberKeyReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JTextArea donorAddress;
    private javax.swing.JTextField donorBlood;
    private javax.swing.JComboBox<String> donorGender;
    private javax.swing.JTextField donorName;
    private javax.swing.JTextField donorNumber;
    private javax.swing.JButton edit;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton profile;
    private javax.swing.JTextField search;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
