/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GPA;

import HOME.HomeFrame;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author raj
 */
public class GPAFrame extends javax.swing.JFrame {

    /**
     * Creates new form GPAFrame
     */
    
    private double totalCredit = 0;
    private double totalPoint = 0;
    private double creditPoint;
    private double gpa;
    private String code;
    private String credit;
    private String point;
    
    
    public GPAFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        closeOperation();
        createIcon();
    }
    
    private void closeOperation() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int c = JOptionPane.showConfirmDialog(null, "Do you want to close it ?","Close Operation",JOptionPane.YES_NO_OPTION);
                if(c == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }
            
        });
    }
    
    private void createIcon(){
        ImageIcon icon = new ImageIcon(getClass().getResource("logo.jpg"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codeTf = new javax.swing.JTextField();
        creditTf = new javax.swing.JTextField();
        pointTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        AddBtn = new javax.swing.JButton();
        ResultBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        result1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        AddBtn1 = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GPA ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Subject Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 82, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Credit");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 169, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Grade Point ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 254, -1, -1));

        codeTf.setBackground(new java.awt.Color(153, 255, 153));
        codeTf.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        getContentPane().add(codeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 74, 173, 40));

        creditTf.setBackground(new java.awt.Color(153, 255, 153));
        creditTf.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        creditTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                creditTfKeyPressed(evt);
            }
        });
        getContentPane().add(creditTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 161, 173, 40));

        pointTf.setBackground(new java.awt.Color(153, 255, 153));
        pointTf.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        pointTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pointTfKeyPressed(evt);
            }
        });
        getContentPane().add(pointTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 246, 173, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ta.setEditable(false);
        ta.setBackground(new java.awt.Color(153, 255, 153));
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 74, 211, 212));

        AddBtn.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 325, 105, -1));

        ResultBtn.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        ResultBtn.setText("Result");
        ResultBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ResultBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 325, 105, -1));

        ResetBtn.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 325, 105, -1));

        result1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        result1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 96, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Code");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Credit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Point");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Your GPA is ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 387, 130, 30));

        result.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 96, 40));

        AddBtn1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        AddBtn1.setText("Add");
        AddBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(AddBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 325, 105, -1));

        HomeBtn.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GPA/gpaF1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        code = codeTf.getText();
        credit = creditTf.getText();
        point = pointTf.getText();
        
        if (code.equals("") || credit.equals("") || point.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all the rows!");
        } else {
            ta.append(code + "     " + credit + "     " + point + "\n");
            creditPoint = Double.parseDouble(credit) * Double.parseDouble(point);
            totalCredit = totalCredit + Double.parseDouble(credit);
            totalPoint = totalPoint + creditPoint;
            
            codeTf.setText("");
            creditTf.setText("");
            pointTf.setText("");
        }

    }//GEN-LAST:event_AddBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        codeTf.setText("");
        creditTf.setText("");
        pointTf.setText("");
        ta.setText("");
        result1.setText("");
        result.setText("");
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void ResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultBtnActionPerformed
        if (!ta.getText().equals("")) {
            gpa = totalPoint / totalCredit;
            if (gpa == 0) {
                result1.setText("F");
            } else if (gpa > 0 && gpa <= 1.0) {
                result1.setText("D");
            } else if (gpa > 1.0 && gpa <= 1.5) {
                result1.setText("C");
            } else if (gpa > 1.5 && gpa <= 2.0) {
                result1.setText("C+");
            } else if (gpa > 2.0 && gpa <= 2.5) {
                result1.setText("B");
            } else if (gpa > 2.5 && gpa <= 3.0) {
                result1.setText("B+");
            } else if (gpa > 3.0 && gpa <= 3.5) {
                result1.setText("A");
            } else if (gpa > 3.5 && gpa <= 4) {
                result1.setText("A+");
            } else if (gpa > 4) {
                result1.setText("A+");
            }
            result.setText(String.valueOf(String.format("%.2f", gpa)));
            
        }
    }//GEN-LAST:event_ResultBtnActionPerformed

    private void creditTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditTfKeyPressed
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            JOptionPane.showMessageDialog(null, "Please enter your subject credit!");
            creditTf.setText("");
        }
    }//GEN-LAST:event_creditTfKeyPressed

    private void pointTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pointTfKeyPressed
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            JOptionPane.showMessageDialog(null, "Please enter your grade point!");
            pointTf.setText("");
        }
    }//GEN-LAST:event_pointTfKeyPressed

    private void AddBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn1ActionPerformed

    }//GEN-LAST:event_AddBtn1ActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        new HomeFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPAFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton AddBtn1;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton ResultBtn;
    private javax.swing.JTextField codeTf;
    private javax.swing.JTextField creditTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pointTf;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result1;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
