/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoveTest;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author raj
 */
public class LoveTest extends javax.swing.JFrame {

    /**
     * Creates new form LoveTest
     */
    public LoveTest() {
        initComponents();
        this.setLocationRelativeTo(null);
        closeOperation();
        createIcon();
    }

    private void closeOperation() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int c = JOptionPane.showConfirmDialog(null, "Do you want to close it ?", "Close Operation", JOptionPane.YES_NO_OPTION);
                if (c == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }

        });
    }

    private void createIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("lovepic_1.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yourName = new javax.swing.JTextField();
        partnerName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Love Test");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 113, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Partner Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 215, -1, -1));

        yourName.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        yourName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yourName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yourNameKeyPressed(evt);
            }
        });
        getContentPane().add(yourName, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 105, 215, -1));

        partnerName.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        partnerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        partnerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                partnerNameKeyPressed(evt);
            }
        });
        getContentPane().add(partnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 207, 215, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 210, 114, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 108, -1, -1));

        result.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 323, 530, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoveTest/love.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        yourName.setText("");
        partnerName.setText("");
        result.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double count = 0;
        String yName = yourName.getText().toLowerCase();
        String pName = partnerName.getText().toLowerCase();
        double len1 = yName.length();
        double len2 = pName.length();
        if (len1 <= 0.0 || len2 <= 0.0) {
            JOptionPane.showMessageDialog(null, "Please enter the next name!");
        } else {

            double num = 100 / len1;
                String n1[] = yName.split("");
                String n2[] = pName.split("");

                for (int i = 0; i < len1; i++) {
                    for (int j = 0; j < len2; j++) {
                        if (n1[i].equals(n2[j])) {
                            count += num;
                            break;
                        }
                    }
                }

                result.setText(pName + "  love's  " + yName + "  " + String.format("%.2f", count) + " %");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void yourNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yourNameKeyPressed
//        char c = evt.getKeyChar();
//        if(!Character.isAlphabetic(c)){
//            JOptionPane.showMessageDialog(null,"Please enter the name!");
//        }
    }//GEN-LAST:event_yourNameKeyPressed

    private void partnerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_partnerNameKeyPressed
//        char c = evt.getKeyChar();
//        if(!Character.isAlphabetic(c)){
//            JOptionPane.showMessageDialog(null,"Please enter the name!");
//        }
    }//GEN-LAST:event_partnerNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoveTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoveTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoveTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoveTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoveTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField partnerName;
    private javax.swing.JLabel result;
    private javax.swing.JTextField yourName;
    // End of variables declaration//GEN-END:variables
}
